// <auto-generated />
using System;
using Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20190812054307_Create_Table_Vehicles")]
    partial class Create_Table_Vehicles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasColumnName("Chassis");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnName("Color");

                    b.Property<DateTime>("DateCreate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateUpdate");

                    b.Property<byte>("PassengerCapacity")
                        .HasColumnName("PassengerCapacity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("Chassis")
                        .IsUnique();

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
